site_name: KITTY Manual

nav:
  - Home: index.md
# - Power: power.md
# - Cartridges: cartridge.md
  - Cartridges and Memory: cartridge.md
  - Interrupts: interrupt.md
  - Video: video.md
  - Audio: audio.md
  - Keyboard: keyboard.md
# - A Sample Program: sample.md
theme: readthedocs